# Refer to docs/yaml-configuration.md for detailed reference on choices that can be made in the configuration file.
# In-line and block comments are shown in Example YAML files in config/examples directory.

env: "dev"
app_name: "retail_ops"

connection:
  name: "sql_retail_ops_connection"
  source_type: "SQLSERVER"

unity_catalog:
  global_uc_catalog: "lf_connect_demo_catalog"
  staging_uc_catalog: "lf_connect_common_staging"
  staging_schema: "gateway_assets"

gateway_pipeline_cluster_policy_name: job_compute_for_spn_for_lf_connect

databases:
  - name: retail_ops_db_one
    uc_catalog: "lf_connect_retail_ops"
    schemas:
      - name: dbo
        use_schema_ingestion: false
        tables:
          - source_table: vendors
          - source_table: products
          - source_table: product_vendors
            destination_table: product_vendors_v1
      - name: inventory
        use_schema_ingestion: false
        tables:
          - source_table: warehouses
          - source_table: stock_items
          - source_table: stock_movements

  - name: retail_ops_db_two
    schemas:
      - name: dbo
        use_schema_ingestion: false
        tables:
          - source_table: vendors
          - source_table: products
          - source_table: product_vendors
      - name: inventory
        use_schema_ingestion: false
        tables:
          - source_table: warehouses
          - source_table: stock_items
          - source_table: stock_movements


gateway_pipeline_cluster_config:
  label: "default"
  node_type_id: "Standard_E4d_v4"
  autoscale:
    min_workers: 0
    max_workers: 0
    mode: ENHANCED
  apply_policy_default_values: false
  enable_local_disk_encryption: false
  custom_tags: {}
  spark_conf: {}
  spark_env_vars: {}
  ssh_public_keys: []

gateway_validation:
  enabled: true
  timeout_minutes: 30
  check_interval_seconds: 15


event_log:
  to_table: true

job:
  common_job_for_all_pipelines: false
  common_schedule:
    quartz_cron_expression: "0 */30 * * * ?"
    timezone_id: "UTC"
  
  per_database_schedules:
    - name: "frequent_sync"
      applies_to: [retail_ops_db_two]
      schedule:
        quartz_cron_expression: "0 */15 * * * ?"
        timezone_id: "UTC"
    - name: "hourly_sync"
      applies_to: ["retail_ops_db_one"]
      schedule:
        quartz_cron_expression: "0 0 * * * ?"
        timezone_id: "UTC"